cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2022_postEE/qqHH_CV_1_C2V_0_kl_1_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2022EE_VBFHHto2B2Tau_1.root --sample VBFnonRes --period 2022EE --config config/global_config.yaml --node_index 1 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2023_preBPix/qqHH_CV_1_C2V_0_kl_1_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2023_VBFHHto2B2Tau_1.root --sample VBFnonRes --period 2023 --config config/global_config.yaml --node_index 1 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2023_postBPix/qqHH_CV_1_C2V_0_kl_1_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2023BPix_VBFHHto2B2Tau_1.root --sample VBFnonRes --period 2023BPix --config config/global_config.yaml --node_index 1

cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2022_postEE/qqHH_CV_1p74_C2V_1p37_kl_14p4_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2022EE_VBFHHto2B2Tau_2.root --sample VBFnonRes --period 2022EE --config config/global_config.yaml --node_index 2 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2023_preBPix/qqHH_CV_1p74_C2V_1p37_kl_14p4_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2023_VBFHHto2B2Tau_2.root --sample VBFnonRes --period 2023 --config config/global_config.yaml --node_index 2 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2023_postBPix/qqHH_CV_1p74_C2V_1p37_kl_14p4_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2023BPix_VBFHHto2B2Tau_2.root --sample VBFnonRes --period 2023BPix --config config/global_config.yaml --node_index 2 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2022_postEE/qqHH_CV_2p12_C2V_3p87_kl_m5p96_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2022EE_VBFHHto2B2Tau_3.root --sample VBFnonRes --period 2022EE --config config/global_config.yaml --node_index 3 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2023_preBPix/qqHH_CV_2p12_C2V_3p87_kl_m5p96_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2023_VBFHHto2B2Tau_3.root --sample VBFnonRes --period 2023 --config config/global_config.yaml --node_index 3 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2023_postBPix/qqHH_CV_2p12_C2V_3p87_kl_m5p96_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2023BPix_VBFHHto2B2Tau_3.root --sample VBFnonRes --period 2023BPix --config config/global_config.yaml --node_index 3

cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2022_preEE/qqHH_CV_m0p758_C2V_1p44_kl_m19p3_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2022_VBFHHto2B2Tau_5.root --sample VBFnonRes --period 2022 --config config/global_config.yaml --node_index 5 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2022_postEE/qqHH_CV_m0p758_C2V_1p44_kl_m19p3_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2022EE_VBFHHto2B2Tau_5.root --sample VBFnonRes --period 2022EE --config config/global_config.yaml --node_index 5 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2023_preBPix/qqHH_CV_m0p758_C2V_1p44_kl_m19p3_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2023_VBFHHto2B2Tau_5.root --sample VBFnonRes --period 2023 --config config/global_config.yaml --node_index 5 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2023_postBPix/qqHH_CV_m0p758_C2V_1p44_kl_m19p3_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2023BPix_VBFHHto2B2Tau_5.root --sample VBFnonRes --period 2023BPix --config config/global_config.yaml --node_index 5 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2022_preEE/qqHH_CV_m0p962_C2V_0p959_kl_m1p43_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2022_VBFHHto2B2Tau_6.root --sample VBFnonRes --period 2022 --config config/global_config.yaml --node_index 6 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2022_postEE/qqHH_CV_m0p962_C2V_0p959_kl_m1p43_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2022EE_VBFHHto2B2Tau_6.root --sample VBFnonRes --period 2022EE --config config/global_config.yaml --node_index 6 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2023_preBPix/qqHH_CV_m0p962_C2V_0p959_kl_m1p43_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2023_VBFHHto2B2Tau_6.root --sample VBFnonRes --period 2023 --config config/global_config.yaml --node_index 6 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2023_postBPix/qqHH_CV_m0p962_C2V_0p959_kl_m1p43_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2023BPix_VBFHHto2B2Tau_6.root --sample VBFnonRes --period 2023BPix --config config/global_config.yaml --node_index 6

cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2022_preEE/qqHH_CV_m1p21_C2V_1p94_kl_m0p94_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2022_VBFHHto2B2Tau_7.root --sample VBFnonRes --period 2022 --config config/global_config.yaml --node_index 7 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2022_postEE/qqHH_CV_m1p21_C2V_1p94_kl_m0p94_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2022EE_VBFHHto2B2Tau_7.root --sample VBFnonRes --period 2022EE --config config/global_config.yaml --node_index 7 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2023_preBPix/qqHH_CV_m1p21_C2V_1p94_kl_m0p94_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2023_VBFHHto2B2Tau_7.root --sample VBFnonRes --period 2023 --config config/global_config.yaml --node_index 7 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2023_postBPix/qqHH_CV_m1p21_C2V_1p94_kl_m0p94_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2023BPix_VBFHHto2B2Tau_7.root --sample VBFnonRes --period 2023BPix --config config/global_config.yaml --node_index 7 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2022_preEE/qqHH_CV_m1p60_C2V_2p72_kl_m1p36_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2022_VBFHHto2B2Tau_8.root --sample VBFnonRes --period 2022 --config config/global_config.yaml --node_index 8 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2022_postEE/qqHH_CV_m1p60_C2V_2p72_kl_m1p36_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2022EE_VBFHHto2B2Tau_8.root --sample VBFnonRes --period 2022EE --config config/global_config.yaml --node_index 8 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2023_preBPix/qqHH_CV_m1p60_C2V_2p72_kl_m1p36_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2023_VBFHHto2B2Tau_8.root --sample VBFnonRes --period 2023 --config config/global_config.yaml --node_index 8 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2023_postBPix/qqHH_CV_m1p60_C2V_2p72_kl_m1p36_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2023BPix_VBFHHto2B2Tau_8.root --sample VBFnonRes --period 2023BPix --config config/global_config.yaml --node_index 8 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2022_preEE/qqHH_CV_m1p83_C2V_3p57_kl_m3p39_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2022_VBFHHto2B2Tau_9.root --sample VBFnonRes --period 2022 --config config/global_config.yaml --node_index 9 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2022_postEE/qqHH_CV_m1p83_C2V_3p57_kl_m3p39_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2022EE_VBFHHto2B2Tau_9.root --sample VBFnonRes --period 2022EE --config config/global_config.yaml --node_index 9 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2023_preBPix/qqHH_CV_m1p83_C2V_3p57_kl_m3p39_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2023_VBFHHto2B2Tau_9.root --sample VBFnonRes --period 2023 --config config/global_config.yaml --node_index 9 && \
cmsEnv python3 Studies/HHVBFjTag/CreateTrainingSkim_CCLUB.py --input /eos/cms/store/group/phys_higgs/HHbbtautau/PreprocessRDF/run3_2023_postBPix/qqHH_CV_m1p83_C2V_3p57_kl_m3p39_hbbhtt/cat_base/Prod_25_09_signalsForVbfjtagTraining/ --outFile /eos/user/e/emartinv/vbfjets_Training/training_skims_0409/2023BPix_VBFHHto2B2Tau_9.root --sample VBFnonRes --period 2023BPix --config config/global_config.yaml --node_index 9