########## tau1 BEGIN ##########
tau1_pt:
  x_bins: [0, 20, 40, 60, 80, 100, 125, 150,175, 200, 250, 300]
  x_title: tau_1 p_{T} (GeV)
  y_title: dN/dm (1/GeV)
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: True

tau1_eta:
  x_bins: "50|-2.5:2.5"
  x_title: tau_1 \eta
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False

tau1_phi:
  x_bins:  "50|-2.5:2.5"
  x_title: tau_1 \phi
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False

tau1_mass:
  x_bins: [0, 20, 40, 60, 80, 100, 125, 150,175, 200, 250, 300]
  x_title: tau_1 p_{T} (GeV)
  y_title: \tau_1 mass (1/GeV)
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: True

tau1_idDeepTau2017v2p1VSe:
  x_bins:  "100|0:10"
  x_title: DeepTau2p1VSe \tau_1
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False

tau1_idDeepTau2017v2p1VSmu:
  x_bins:  "100|0:10"
  x_title: DeepTau2p1VSmu \tau_1
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False

tau1_idDeepTau2017v2p1VSjet:
  x_bins:  "100|0:10"
  x_title: DeepTau2p1VSjet \tau_1
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False


tau1_idDeepTau2018v2p5VSe:
  x_bins:  "100|0:10"
  x_title: DeepTau2p5VSe \tau_1
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False

tau1_idDeepTau2018v2p5VSmu:
  x_bins:  "100|0:10"
  x_title: DeepTau2p5VSmu \tau_1
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False

tau1_idDeepTau2018v2p5VSjet:
  x_bins:  "100|0:10"
  x_title: DeepTau2p5VSjet \tau_1
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False

tau1_charge:
  x_bins: "20|-2.5:2.5"
  x_title: tau_1 charge
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False

tau1_iso:
  x_bins: "100|0:10"
  x_title: tau_1 iso
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False

########## tau1 END ##########

########## tau2 BEGIN ##########
tau2_pt:
  x_bins: [0, 20, 40, 60, 80, 100, 125, 150,175, 200, 250, 300]
  x_title: tau_1 p_{T} (GeV)
  y_title: dN/dm (1/GeV)
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: True

tau2_eta:
  x_bins:  "50|-2.5:2.5"
  x_title: tau_1 \eta
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False

tau2_phi:
  x_bins:  "50|-2.5:2.5"
  x_title: tau_1 \phi
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False

tau2_mass:
  x_bins: [0, 20, 40, 60, 80, 100, 125, 150,175, 200, 250, 300]
  x_title: tau_1 p_{T} (GeV)
  y_title: \tau_1 mass (1/GeV)
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: True

tau2_idDeepTau2017v2p1VSe:
  x_bins:  "100|0:10"
  x_title: DeepTau2p1VSe \tau_1
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False

tau2_idDeepTau2017v2p1VSmu:
  x_bins:  "100|0:10"
  x_title: DeepTau2p1VSmu \tau_1
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False

tau2_idDeepTau2017v2p1VSjet:
  x_bins:  "100|0:10"
  x_title: DeepTau2p1VSjet \tau_1
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False


tau2_idDeepTau2018v2p5VSe:
  x_bins:  "100|0:10"
  x_title: DeepTau2p5VSe \tau_1
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False

tau2_idDeepTau2018v2p5VSmu:
  x_bins:  "100|0:10"
  x_title: DeepTau2p5VSmu \tau_1
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False

tau2_idDeepTau2018v2p5VSjet:
  x_bins:  "100|0:10"
  x_title: DeepTau2p5VSjet \tau_1
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False

tau2_charge:
  x_bins: "20|-2.5:2.5"
  x_title: tau_1 charge
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False

tau2_iso:
  x_bins: "100|0:10"
  x_title: tau_1 iso
  y_title: Events
  use_log_y: False
  max_y_sf: 1.6
  divide_by_bin_width: False

########## tau2 END ##########

########## b1 BEGIN ##########
b1_pt:
  x_bins: [0, 20, 40, 60, 80, 100, 125, 150,175, 200, 250, 300]
  x_title: b-jet_1 p_{T} (GeV)
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False


b1_eta:
  x_bins:  "50|-2.5:2.5"
  x_title: b-jet_1 \eta
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

b1_phi:
  x_bins:  "70|-3.5:3.5"
  x_title: b-jet_1 \phi
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

b1_mass:
  x_bins:  "40|0:80"
  x_title: b-jet_1 mass
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

b1_btagDeepFlavB:
  x_bins:  "20|0.:1."
  x_title: b-jet_1 deepFlavB
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

b1_btagDeepFlavCvB:
  x_bins:  "20|0.:1."
  x_title: b-jet_1 DeepFlavCvB
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

b1_btagDeepFlavCvL:
  x_bins:  "20|0.:1."
  x_title: b-jet_1 DeepFlavCvL
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False


b1_particleNetAK4_B:
  x_bins:  "20|0.:1."
  x_title: b-jet_1 particleNetAK4 B
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

b1_particleNetAK4_CvsB:
  x_bins:  "20|0.:1."
  x_title: b-jet_1 particleNetAK4 CvsB
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

b1_particleNetAK4_CvsL:
  x_bins:  "20|0.:1."
  x_title: b-jet_1 particleNetAK4 CvsL
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False


b1_HHbtag:
  x_bins:  "40|0.:2."
  x_title: b-jet_1 HHbtag
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False


b1_hadronFlavour:
  x_bins:  "7|-0.5:6.7"
  x_title: b-jet_1 hadronFlavour
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

########## b1 END ##########


########## b2 BEGIN ##########

b2_pt:
  x_bins: [0, 20, 40, 60, 80, 100, 125, 150,175, 200, 250, 300]
  x_title: b-jet_2 p_{T} (GeV)
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False


b2_eta:
  x_bins:  "50|-2.5:2.5"
  x_title: b-jet_2 \eta
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

b2_phi:
  x_bins:  "70|-3.5:3.5"
  x_title: b-jet_2 \phi
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

b2_mass:
  x_bins:  "40|0:80"
  x_title: b-jet_2 mass
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

b2_btagDeepFlavB:
  x_bins:  "20|0.:1."
  x_title: b-jet_2 deepFlavB
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

b2_btagDeepFlavCvB:
  x_bins:  "20|0.:1."
  x_title: b-jet_2 DeepFlavCvB
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

b2_btagDeepFlavCvL:
  x_bins:  "20|0.:1."
  x_title: b-jet_2 DeepFlavCvL
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False


b2_particleNetAK4_B:
  x_bins:  "20|0.:1."
  x_title: b-jet_2 particleNetAK4 B
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

b2_particleNetAK4_CvsB:
  x_bins:  "20|0.:1."
  x_title: b-jet_2 particleNetAK4 CvsB
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

b2_particleNetAK4_CvsL:
  x_bins:  "20|0.:1."
  x_title: b-jet_2 particleNetAK4 CvsL
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False


b2_HHbtag:
  x_bins:  "40|0.:2."
  x_title: b-jet_2 HHbtag
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False


b2_hadronFlavour:
  x_bins:  "7|-0.5:6.7"
  x_title: b-jet_2 hadronFlavour
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

########## b2 END ##########

tautau_m_vis:
  x_bins: [0, 40, 60, 80, 100, 120, 140, 160,180, 200, 250, 300, 350, 400, 450, 500, 1000]
  x_title: M^{\tau\tau}_{vis} (GeV)
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

bb_m_vis:
  x_bins: [0, 40, 60, 80, 100, 120, 140, 160,180, 200, 250, 300, 350, 400, 450, 500, 1000]
  x_title: M^{bb}(GeV)
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

bbtautau_mass:
  x_bins: [250, 280, 300, 350, 400, 450, 500, 550, 600, 700, 800, 900, 1000, 1500, 2000,3000]
  x_title: M^{HH}_{vis} (GeV)
  y_title: Events
  use_log_y: True
  max_y_sf: 300
  divide_by_bin_width: False

dR_tautau:
  x_bins: "10|0:5"
  x_title: \Delta R(\tau\tau)
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

nBJets:
  x_bins: "13|-0.5:12.5"
  x_title: n_bJets
  y_title: Events
  use_log_y: True
  max_y_sf: 1.6
  divide_by_bin_width: False



########## MET BEGIN ##########
met_pt:
  x_bins : [0,20,40,60,80,100,125,150,175,200,250,300]
  x_title : P_{T}^{miss} (GeV)
  y_title : dN/dm (1/GeV)
  max_y_sf : 1.6
  use_log_y: False
  divide_by_bin_width: False

met_phi:
  x_bins: "20|0:3.2"
  x_title: \phi_{E_{T}^{miss}}
  y_title: Events
  max_y_sf: 1.5
  use_log_y: False
  divide_by_bin_width: False

########## MET END ##########

##########  Kinfit ##########
kinFit_convergence:
  x_bins: "11|-1.5:9.5"
  x_title: KinFit convergence
  y_title: Events
  max_y_sf: 1.5
  use_log_y: False
  divide_by_bin_width: False

kinFit_result_probability:
  x_bins: "20|-0.5:1.5"
  x_title: KinFit prob
  y_title: Events
  max_y_sf: 1.5
  use_log_y: False
  divide_by_bin_width: False

kinFit_m:
  x_bins: [250,260,270,280,290,300,325,350,375,400,425,450,475,500,550,600,650,700,850,1000,1150,1300,1500,1750,2000]
  #x_bins:[250, 400, 500,600,700,850,1000,1150,1300,1500,1750,2000]
  x_title: M_{H}^{kinfit} (GeV)
  y_title: dN/dm_{H}^{kinfit} (1/GeV)
  max_y_sf: 1.4
  divide_by_bin_width: False
  use_log_y: False

kinFit_chi2:
  x_bins: [0,20,40,60,80,100,150,200]
  x_title: KinFit \chi^{2}
  y_title: Events
  max_y_sf: 2
  divide_by_bin_width: False
  use_log_y: False
  #x_bins:0:200/50 x_title="KinFit #chi^{2}" y_title="Events" max_y_sf=2

########## SVfit, Kinfit, MT2 BEGIN ##########
SVfit_valid:
  x_bins: "2|-0.5:1.5"
  x_title: SVfit valid
  y_title: Events
  max_y_sf: 1.5
  divide_by_bin_width: False
  use_log_y: False

SVfit_pt:
  x_bins: [0,20,40,60,80,100,125,150,175,200,250,300]
  x_title: SVfit P_{T}(GeV)
  y_title: dN/dm (1/GeV)
  max_y_sf: 1.6
  divide_by_bin_width: False
  use_log_y: False

SVfit_pt_error:
  x_bins: [0,20,40,60,80,100,125,150,175,200,250,300]
  x_title: SVfit P_{T} error(GeV)
  y_title: dN/dm (1/GeV)
  max_y_sf: 1.6
  divide_by_bin_width: False
  use_log_y: False

SVfit_eta:
  x_bins: "50|-2.5:2.5"
  x_title: SVfit \eta
  y_title: Events
  max_y_sf: 1.6
  divide_by_bin_width: False
  use_log_y: False

SVfit_eta_error:
  x_bins: "50|-2.5:2.5"
  x_title: SVfit \eta error
  y_title: Events" max_y_sf=1.
  divide_by_bin_width: False
  use_log_y: False

SVfit_phi:
  x_bins: "70|-3.5:3.5"
  x_title: SVfit \phi
  y_title: Events
  max_y_sf: 1.6
  divide_by_bin_width: False
  use_log_y: False

SVfit_phi_error:
  x_bins:  "70|-3.5:3.5"
  x_title: SVfit \phi error
  y_title: Events
  max_y_sf: 1.6
  divide_by_bin_width: False
  use_log_y: False

SVfit_m:
  x_bins: [60,75,90,105,120,135,150,175,210,250,300,350,400,500]
  x_title: SVfit M_{\tau\tau} (GeV)
  y_title: dN/dm_{\tau\tau} (1/GeV)
  max_y_sf: 1.6
  divide_by_bin_width: False
  use_log_y: False

SVfit_m_error:
  x_bins: [60,75,90,105,120,135,150,175,210,250,300,350,400,500]
  y_title: dN/dm_{\tau\tau} (1/GeV)
  max_y_sf: 1.6
  divide_by_bin_width: False
  use_log_y: False

SVfit_mt:
  x_bins: [0,20,40,60,80,100,125,150,175,200,250,300]
  x_title: SVfit M_{T}(GeV)
  y_title: dN/dm_{\tau\tau} (1/GeV)
  max_y_sf: 1.6
  divide_by_bin_width: False
  use_log_y: False

SVfit_mt_error:
  x_bins: [0,20,40,60,80,100,125,150,175,200,250,300]
  x_title: SVfit M_{T}(GeV) error
  y_title: dN/dm_{\tau\tau} (1/GeV)
  max_y_sf: 1.6
  divide_by_bin_width: False
  use_log_y: False
MT2:
  x_bins: [0,25,50,75,100,125,150,175,200,250,300,500]
  x_title: MT2_{H} (GeV)
  max_y_sf: 1.6
  divide_by_bin_width: False
  use_log_y: False
########## SVfit, Kinfit, MT2 END ##########