- name: DY
  title: "DY #rightarrow ll + jets"
  color: kAzure+10
- name: TT
  title: t#bar{t}
  color: kGreen-3
- name: W
  title: "W #rightarrow l#nu + jets"
  color: kYellow-7
- name: HHnonRes
  title: "HH SM"
  color: kRed-4
- name: GluGluToBulkGraviton
  title: "GluGluBulkGraviton"
  type: signal
  color: kBlue
  #scale: 5
- name: GluGluToRadion
  title: "GluGluRadion"
  type: signal
  color: kCyan
  #scale: 5
#- name: VBFToBulkGraviton
#  title: "qqHH #rightarrow bb#tau#tau BulkGraviton"
#  type: signal
#  color: kMagenta
#  scale: 5
#- name: VBFToRadion
#  title: "qqHH #rightarrow bb#tau#tau Radion"
#  type: signal
#  color: kViolet+4
#  scale: 5
- name: QCD
  title: QCD
  color: kOrange
- name: Other
  title: "other backgrounds"
  color: kPink+1
- name: data
  title: "data"
  type: data
