cmsswPython: RunKit/nanoProdWrapper.py
params:
  customise: Framework/NanoProd/customiseNano.customise
  skimCfg: skim.yaml
  maxEvents: -1
splitting: FileBased
unitsPerJob: 8
scriptExe: RunKit/crabJob.sh
outputFiles:
  - nano.root
filesToTransfer:
  - RunKit/crabJob.sh
  - RunKit/crabJob.py
  - RunKit/crabJob_nanoProd.py
  - RunKit/skim_tree.py
  - RunKit/sh_tools.py
  - config/skim.yaml
  - Common/skimNano.py
  - Common/BaselineSelection.py
  - Common/AnalysisTools.h
  - Common/BaselineGenSelection.h
  - Common/BaselineRecoSelection.h
  - Common/exception.h
  - Common/GenLepton.h
  - Common/GenStatusFlags.h
  - Common/GenTools.h
  - Common/HHCore.h
  - Common/TextIO.h
  - Common/Utilities.py

# Update destination site and paths before launching a production
site: T3_CH_CERNBOX
crabOutput: /store/user/kandroso/bbtt-prod
localCrabOutput: /eos/home-k/kandroso/bbtt-prod
finalOutput: /eos/home-k/kandroso/bbtt/nanoV10

maxMemory: 2500
numCores: 1
inputDBS: global
allowNonValid: False
dryrun: False
maxRecoveryCount: 3
updateInterval: 60 # minutes
localProcessing:
  lawTask: ProdTask
  workflow: htcondor
  bootstrap: bootstrap.sh
#  requirements: ( (OpSysAndVer =?= "CentOS7") || (OpSysAndVer =?= "CentOS8") )
targetOutputFileSize: 2048 # MiB
renewKerberosTicket: True
whitelistFinalRecovery:
  - T1_DE_KIT
  - T2_CH_CERN
  - T2_DE_DESY
  - T2_IT_Legnaro
  - T3_CH_PSI